const fs = require('fs');
const path = require('path');

const projects = [
  {
    name: "01-Neon-Buton",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Neon Buton</title><link rel="stylesheet" href="style.css"></head><body><button class="neon-buton">BANA TIKLA</button><script src="script.js"></script></body></html>`,
    css: `body { margin: 0; height: 100vh; background-color: #050801; display: flex; justify-content: center; align-items: center; font-family: 'Arial', sans-serif; } .neon-buton { position: relative; padding: 15px 30px; color: #03e9f4; text-decoration: none; font-size: 24px; text-transform: uppercase; letter-spacing: 4px; background: transparent; border: 2px solid #03e9f4; border-radius: 5px; cursor: pointer; transition: 0.5s; } .neon-buton:hover { background: #03e9f4; color: #050801; box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4; }`,
    js: `// Sadece CSS kullanildi`
  },
  {
    name: "02-Kalp-Patlamasi",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Kalp Patlamasi</title><link rel="stylesheet" href="style.css"></head><body><button class="neon-buton" id="btn">BANA TIKLA</button><div id="kalp-konteyner"></div><div class="merkez-harf" id="harf">Y</div><script src="script.js"></script></body></html>`,
    css: `body { background-color: #050801; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; overflow: hidden; font-family: 'Arial', sans-serif; } .neon-buton { position: relative; padding: 15px 30px; color: #03e9f4; text-decoration: none; font-size: 24px; text-transform: uppercase; letter-spacing: 4px; background: transparent; border: 2px solid #03e9f4; border-radius: 5px; cursor: pointer; transition: 0.5s; z-index: 10; } .neon-buton:hover { background: #03e9f4; color: #050801; box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4; } .gizle { display: none !important; } .merkez-harf { color: #fff; font-size: 10rem; font-weight: bold; text-shadow: 0 0 10px #ff007f, 0 0 20px #ff007f, 0 0 40px #ff007f, 0 0 80px #ff007f; opacity: 0; transform: scale(0.1); position: absolute; transition: all 1.5s ease-in-out; z-index: 5; } .merkez-harf.goster { opacity: 1; transform: scale(1); } .kalp { position: absolute; opacity: 0; transform: scale(0); animation: kalpBuyu 2s forwards ease-out; } @keyframes kalpBuyu { 0% { transform: scale(0) translateY(0); opacity: 0; } 50% { opacity: 1; } 100% { transform: scale(1.2) translateY(-100px); opacity: 0; } }`,
    js: `const btn = document.getElementById('btn'); const harf = document.getElementById('harf'); const konteyner = document.getElementById('kalp-konteyner'); const renkler = ['#ff007f', '#ff003c', '#e900ff', '#00e1ff', '#ffea00']; btn.addEventListener('click', () => { btn.classList.add('gizle'); harf.classList.add('goster'); for (let i = 0; i < 40; i++) { setTimeout(() => { const kalp = document.createElement('div'); kalp.innerHTML = '❤️'; kalp.classList.add('kalp'); const x = Math.random() * window.innerWidth; const y = Math.random() * window.innerHeight; kalp.style.left = \`\${x}px\`; kalp.style.top = \`\${y}px\`; const rastgeleRenk = renkler[Math.floor(Math.random() * renkler.length)]; kalp.style.textShadow = \`0 0 20px \${rastgeleRenk}, 0 0 40px \${rastgeleRenk}\`; kalp.style.fontSize = \`\${Math.random() * 3 + 1}rem\`; konteyner.appendChild(kalp); }, i * 40); } });`
  },
  {
    name: "03-Seni-Seviyorum",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Seni Seviyorum</title><link rel="stylesheet" href="style.css"></head><body><button class="neon-buton" id="btn">BANA TIKLA</button><h1 class="gizli-yazi" id="yazi">Seni Seviyorum ❤️</h1><script src="script.js"></script></body></html>`,
    css: `body { background-color: #050801; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; overflow: hidden; font-family: 'Arial', sans-serif; } .neon-buton { position: relative; padding: 15px 30px; color: #03e9f4; text-decoration: none; font-size: 24px; text-transform: uppercase; letter-spacing: 4px; background: transparent; border: 2px solid #03e9f4; border-radius: 5px; cursor: pointer; transition: 0.5s; } .neon-buton:hover { background: #03e9f4; color: #050801; box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4; } .gizle { display: none !important; } .gizli-yazi { color: #ff003c; font-size: 5rem; text-align: center; text-shadow: 0 0 10px #ff003c, 0 0 20px #ff003c, 0 0 40px #ff003c, 0 0 80px #ff003c; opacity: 0; transform: scale(0.1); position: absolute; transition: all 1.5s ease-in-out; pointer-events: none; } .goster { opacity: 1; transform: scale(1); }`,
    js: `const btn = document.getElementById('btn'); const yazi = document.getElementById('yazi'); btn.addEventListener('click', () => { btn.classList.add('gizle'); yazi.classList.add('goster'); });`
  },
  {
    name: "04-Glassmorphism",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Cam Kart</title><link rel="stylesheet" href="style.css"></head><body><div class="renkli-top-1"></div><div class="renkli-top-2"></div><div class="cam-kart"><div class="kart-ust"><div class="kart-logo">BANK</div><div class="cip"></div></div><div class="kart-numarasi">4000 1234 5678 9010</div><div class="kart-alt"><span>Geçerlilik: 12/28</span><span>CVV: ***</span></div></div><script src="script.js"></script></body></html>`,
    css: `body { margin: 0; height: 100vh; background-color: #1a1a2e; display: flex; justify-content: center; align-items: center; font-family: 'Arial', sans-serif; overflow: hidden; } .renkli-top-1, .renkli-top-2 { position: absolute; border-radius: 50%; filter: blur(60px); z-index: -1; animation: yuzme 8s infinite alternate; } .renkli-top-1 { width: 300px; height: 300px; background: #ff007f; top: 15%; left: 30%; } .renkli-top-2 { width: 400px; height: 400px; background: #00e1ff; bottom: 10%; right: 25%; } @keyframes yuzme { from { transform: translate(0, 0); } to { transform: translate(60px, -60px) scale(1.1); } } .cam-kart { width: 380px; height: 230px; background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); -webkit-backdrop-filter: blur(15px); border: 1px solid rgba(255, 255, 255, 0.3); border-radius: 20px; box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2); display: flex; flex-direction: column; justify-content: space-between; padding: 30px; color: #fff; cursor: pointer; transition: transform 0.4s ease; } .cam-kart:hover { transform: translateY(-15px); } .kart-ust { display: flex; justify-content: space-between; align-items: center; } .kart-logo { font-size: 1.5rem; font-weight: bold; letter-spacing: 2px; } .cip { width: 45px; height: 35px; background: rgba(255, 255, 255, 0.4); border-radius: 6px; } .kart-numarasi { font-size: 1.4rem; letter-spacing: 5px; margin-top: 40px; } .kart-alt { display: flex; justify-content: space-between; font-size: 0.9rem; opacity: 0.8; }`,
    js: `// Sadece CSS kullanildi`
  },
  {
    name: "05-Cizilen-Lazer-Kalp",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Lazer Kalp</title><link rel="stylesheet" href="style.css"></head><body><canvas id="kalpTuvali"></canvas><script src="script.js"></script></body></html>`,
    css: `body { margin: 0; height: 100vh; background-color: #000; display: flex; justify-content: center; align-items: center; overflow: hidden; }`,
    js: `const canvas = document.getElementById('kalpTuvali'); const ctx = canvas.getContext('2d'); canvas.width = window.innerWidth; canvas.height = window.innerHeight; const merkezX = canvas.width / 2; const merkezY = canvas.height / 2; const renkler = ["#ff0000", "#0055ff", "#00ff00", "#ffff00", "#00ffff", "#ff00ff", "#ffa500", "#ffc0cb"]; let i = 0; const toplamCizgi = 120; function kalpCiz() { if (i >= toplamCizgi) return; const aci = i * (Math.PI * 2) / toplamCizgi; const x = 16 * Math.pow(Math.sin(aci), 3); const y = 13 * Math.cos(aci) - 5 * Math.cos(2 * aci) - 2 * Math.cos(3 * aci) - Math.cos(4 * aci); const renk = renkler[Math.floor(Math.random() * renkler.length)]; ctx.strokeStyle = renk; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(merkezX, merkezY - 50); const hedefX = merkezX + (x * 15); const hedefY = merkezY - (y * 15) - 50; ctx.lineTo(hedefX, hedefY); ctx.stroke(); ctx.fillStyle = renk; ctx.beginPath(); ctx.arc(hedefX, hedefY, 2.5, 0, Math.PI * 2); ctx.fill(); i++; setTimeout(kalpCiz, 40); } kalpCiz();`
  },
  {
    name: "06-Matrix-Yagmuru",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Matrix</title><link rel="stylesheet" href="style.css"></head><body><canvas id="matrixTuvali"></canvas><script src="script.js"></script></body></html>`,
    css: `body { margin: 0; padding: 0; height: 100vh; background-color: #000; overflow: hidden; } canvas { display: block; }`,
    js: `const canvas = document.getElementById('matrixTuvali'); const ctx = canvas.getContext('2d'); canvas.width = window.innerWidth; canvas.height = window.innerHeight; const harfler = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*'; const harfDizisi = harfler.split(''); const fontBoyutu = 16; const sutunSayisi = canvas.width / fontBoyutu; const damlalar = []; for (let x = 0; x < sutunSayisi; x++) { damlalar[x] = 1; } function matrixYagdir() { ctx.fillStyle = 'rgba(0, 0, 0, 0.05)'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = '#0f0'; ctx.font = fontBoyutu + 'px monospace'; for (let i = 0; i < damlalar.length; i++) { const rastgeleHarf = harfDizisi[Math.floor(Math.random() * harfDizisi.length)]; ctx.fillText(rastgeleHarf, i * fontBoyutu, damlalar[i] * fontBoyutu); if (damlalar[i] * fontBoyutu > canvas.height && Math.random() > 0.975) { damlalar[i] = 0; } damlalar[i]++; } } setInterval(matrixYagdir, 33);`
  },
  {
    name: "07-Sifre-Cozucu-Yazi",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Sifre Cozucu</title><link rel="stylesheet" href="style.css"></head><body><h1 class="sifreli-yazi" data-deger="FRONTEND DEVELOPER">FRONTEND DEVELOPER</h1><script src="script.js"></script></body></html>`,
    css: `body { margin: 0; height: 100vh; background-color: #050801; display: flex; justify-content: center; align-items: center; font-family: 'Courier New', monospace; } .sifreli-yazi { color: #4a90e2; font-size: 5vw; font-weight: bold; letter-spacing: 5px; cursor: pointer; text-shadow: 0 0 10px #0033cc, 0 0 20px #0022aa, 0 0 40px #001166; }`,
    js: `const harfler = "ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*"; const yazi = document.querySelector(".sifreli-yazi"); function sifreyiCoz() { let adim = 0; clearInterval(yazi.interval); yazi.interval = setInterval(() => { yazi.innerText = yazi.innerText.split("").map((harf, index) => { if (index < adim) { return yazi.dataset.deger[index]; } return harfler[Math.floor(Math.random() * harfler.length)]; }).join(""); if (adim >= yazi.dataset.deger.length) { clearInterval(yazi.interval); } adim += 1 / 8; }, 40); } sifreyiCoz(); yazi.onmouseover = sifreyiCoz;`
  },
  {
    name: "08-Dark-Mode-Gecis",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Dark Mode</title><link rel="stylesheet" href="style.css"></head><body><label class="tema-dugmesi"><input type="checkbox" id="tema-gecis"><span class="kaydirici"><div class="gezegen"></div></span></label><script src="script.js"></script></body></html>`,
    css: `body { margin: 0; height: 100vh; display: flex; justify-content: center; align-items: center; background-color: #e0e5ec; transition: background-color 0.8s ease; } body.karanlik { background-color: #1a1a2e; } .tema-dugmesi { position: relative; width: 130px; height: 60px; cursor: pointer; } .tema-dugmesi input { opacity: 0; width: 0; height: 0; } .kaydirici { position: absolute; top: 0; left: 0; right: 0; bottom: 0; background-color: #87ceeb; border-radius: 60px; transition: 0.8s; box-shadow: inset 0 0 10px rgba(0,0,0,0.1); } .gezegen { position: absolute; height: 46px; width: 46px; left: 7px; bottom: 7px; background-color: #ffcc00; border-radius: 50%; transition: 0.8s; box-shadow: 0 0 20px #ffcc00; } input:checked + .kaydirici { background-color: #0f172a; } input:checked + .kaydirici .gezegen { transform: translateX(70px); background-color: transparent; box-shadow: inset -15px -5px 0px 0px #fff; }`,
    js: `const dugme = document.getElementById('tema-gecis'); const sayfa = document.body; dugme.addEventListener('change', () => { if(dugme.checked) { sayfa.classList.add('karanlik'); } else { sayfa.classList.remove('karanlik'); } });`
  },
  {
    name: "09-3D-Suzulen-Kalp",
    html: `<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>3D Kalp</title><link rel="stylesheet" href="style.css"></head><body><div id="sahne"></div><script src="script.js"></script></body></html>`,
    css: `body { margin: 0; height: 100vh; background-color: #000; display: flex; justify-content: center; align-items: center; overflow: hidden; perspective: 1200px; } #sahne { position: relative; width: 100%; height: 100%; transform-style: preserve-3d; animation: sahneDonus 15s linear infinite; } .yazi { position: absolute; color: #ea80b0; font-size: 1.2rem; font-family: monospace; font-weight: bold; white-space: nowrap; text-shadow: 0 0 10px #ea80b0, 0 0 20px #ea80b0; animation: dalgaHareket 3000ms infinite alternate ease-in-out; animation-delay: calc(var(--i) * -150ms); } @keyframes dalgaHareket { 0% { transform: translateZ(calc(var(--z) - 50px)) rotateZ(-10deg) scale(0.9); opacity: 0.7; } 100% { transform: translateZ(calc(var(--z) + 50px)) rotateZ(10deg) scale(1.1); opacity: 1; color: #fff; } } @keyframes sahneDonus { 0% { transform: rotateY(0deg) rotateX(15deg); } 100% { transform: rotateY(360deg) rotateX(15deg); } }`,
    js: `const sahne = document.getElementById('sahne'); const yaziSayisi = 65; const satirlar = 4; for (let k = 0; k < satirlar; k++) { const derinlik = (k - 1.5) * 35; for (let i = 0; i < yaziSayisi; i++) { const t = i * (Math.PI * 2) / yaziSayisi; const x = 16 * Math.pow(Math.sin(t), 3) * 14; const y = -(13 * Math.cos(t) - 5 * Math.cos(2*t) - 2 * Math.cos(3*t) - Math.cos(4*t)) * 14; const yazi = document.createElement('div'); yazi.className = 'yazi'; yazi.style.setProperty('--i', i + (k * 10)); yazi.style.left = \`calc(50% + \${x}px)\`; yazi.style.top = \`calc(50% + \${y}px)\`; yazi.style.setProperty('--z', \`\${derinlik}px\`); yazi.innerHTML = 'I love you'; sahne.appendChild(yazi); } }`
  }
];

projects.forEach(proj => {
  const dirPath = path.join(process.cwd(), proj.name);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
  fs.writeFileSync(path.join(dirPath, 'index.html'), proj.html);
  fs.writeFileSync(path.join(dirPath, 'style.css'), proj.css);
  fs.writeFileSync(path.join(dirPath, 'script.js'), proj.js);
});
console.log('All projects created successfully!');
